### ISSUE TITLE
Keybindings not triggering in vscode

### ISSUE THREAD

**Issue by jog068** [POP303U/vscode-nvim#1]
Hi, I tried to get this to work on my vscode. So far most of its working. I was wondering how you get the keybindings to work? I am not able to reproduce. I was hoping you could help me. Feel free to leave me a message on discord: tayto_potato#0

**Comment by POP303U** [comment]
Glad you are liking my neovim config! Could you tell which keybinds in particular are not working? All the specified keybinds in the keymaps.lua should work if all plugins are installed and synced.

**Comment by POP303U** [comment]
PS: Can you add your full discord tag for example: pops#5376 yours doesn't work.

**Comment by jog068** [comment]
I sent you a friend request. And the keybindings work in neovim, but not in vscode. I am not sure if I have to add any configuration on vscode for the space bar.
